### ISSUE TITLE
Could not find gem 'alchemy_cloudinary' in any of the gem sources listed in your Gemfile

### ISSUE THREAD

**Issue by agorneo** [AlchemyCMS/alchemy_cloudinary#1]
When I follow the directions (README.md) i get the message from bundle:
> Could not find gem 'alchemy_cloudinary' in any of the gem sources listed in your Gemfile

When I went to rubygems, I could not find this gem:
https://rubygems.org/search?utf8=%E2%9C%93&query=alchemy_cloudinary

I forced to use the github version:
`gem 'alchemy_cloudinary', github: 'AlchemyCMS/alchemy_cloudinary'`

**Comment by tvdeyen** [comment]
Yes, this gem is not yet published on Rubygems.org. I want to add some tests before I release a 1.0
